base_config: base.yaml
exp_name: "med_qlora_counsel"
stages:
  - name: stage1_factual
    enabled: false
    file: stage1_factual.jsonl
    num_epochs: 0
  - name: stage2_counseling
    enabled: true
    file: stage2_counseling.jsonl
    num_epochs: 1
    sample_size: 120000
